version: '3'

services:

    app:
        build: 
            args:
                user: sammy
                uid: 1000
            context: ./
        container_name: pokedex-app
        working_dir: /var/www/
        volumes:
            - .:/var/www
        networks:
            - rocha

    nginx:
        build: .docker/nginx
        restart: always
        container_name: pokedex-web
        tty: true
        ports:
            - "8083:80"
        volumes:
            - .:/var/www
        networks:
            - rocha
        depends_on:
            - app

networks:
    rocha:
        external: true
