version: '3'

services:

    app:
        build: .
        entrypoint: dockerize -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
        environment:
            - _DB_HOST=db
            - _DB_DATABASE=laravel
            - _DB_USERNAME=root
            - _DB_PASSWORD=root
        volumes:
            - .:/var/www
        networks:
            - app-network
        depends_on:
            - db

    nginx:
        build: .docker/nginx
        restart: always
        tty: true
        ports:
            - "8083:80"
        volumes:
            - .:/var/www
        networks:
            - app-network
        depends_on:
            - app


networks:
    app-network:
        driver: bridge
