version: '3'
services:
    db:
        container_name: db
        hostname: "db"
        cap_add:
            - SYS_NICE # CAP_SYS_NICE
        build:
            context: .
            dockerfile: ./db/db.dockerfile
        command: --innodb-use-native-aio=0
        restart: always
        tty: true
        ports:
            - "3306:3306"
        volumes:
            - ./docker/db/dbdata:/var/lib/mysql
            - ./docker/db:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - rocha
networks:
    rocha:
        name: rocha
        driver: bridge